#This playbbok will install HTTP server,wget and vim package using loops.

---
- hosts: localhost
  become: true
  gather_facts: no
  tasks:
    - name: Install list of packages
      yum: name='{{item}}' state=absent
      with_items:
       - httpd
       - wget
       - vim
       - zip
       
